// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PickANick.Core.ViewModels;
using PickANick.Core;

namespace PickANick.iOS
{
	public partial class ResultController : UIViewController
	{
		private readonly NickViewModel _nickViewModel = ServiceContainer.Resolve<NickViewModel>();
		public ResultController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_restartButton.TouchUpInside += (sender, e) => {
				NavigationController.PopToRootViewController(true);
			};

			try{
			await _nickViewModel.GetLocation ();
			await _nickViewModel.GetItem ();
			}
			catch(Exception e)
			{
				Console.WriteLine (e);
			}
			if (_nickViewModel.Location.Local)
			{
				_imageLocation.Image = UIImage.FromFile (_nickViewModel.Location.ImageName);
			}
			else
			{
				_imageLocation.Image = UIImage.LoadFromData (NSData.FromUrl(new NSUrl(_nickViewModel.Location.ImageName)));
			}
			_imageNic.Image = UIImage.FromFile (_nickViewModel.PickedNick.ImageName);
			_imageThing.Image = UIImage.FromFile (_nickViewModel.Item.ImageName);
			_nickViewModel.GetStrings ();
			_textGreetings.Text = _nickViewModel.GreetingString;
			_textGreetings2.Text = _nickViewModel.GreetingString;
			_resultText.Text = _nickViewModel.ResultString;
			_restartButton.TitleLabel.Lines = 2;

			_saveButton.TouchUpInside += (sender, e) => {
				ScreenCapture ();
				new UIAlertView ("Congratulations!", "Your Nic is waiting for you in your photo album.", null, "Ok").Show ();
			};


		}

		public void ScreenCapture()
		{

			Console.WriteLine("start capture of frame: " + new System.Drawing.SizeF(320,149));
			UIGraphics.BeginImageContext(new System.Drawing.SizeF(320,149)); 
			var ctx = UIGraphics.GetCurrentContext();
			if (ctx != null)
			{
				View.Layer.RenderInContext(ctx);
				UIImage img = UIGraphics.GetImageFromCurrentImageContext();
				UIGraphics.EndImageContext();

				// Set to display in a UIImage control _on_ the view
				//imageLogo.Image = img;

				// Save to Photos
				img.SaveToPhotosAlbum(
					(sender, args)=>{Console.WriteLine("image saved to Photos");}
				);
			}
			else
			{
				Console.WriteLine("ctx null - doesn't seem to happen");
			}
		}
	}
}
