// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PickANick.Core.ViewModels;
using PickANick.Core;

namespace PickANick.iOS
{
	public partial class ResultController : UIViewController
	{
		private readonly NickViewModel _nickViewModel = ServiceContainer.Resolve<NickViewModel>();
		public ResultController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_restartButton.TouchUpInside += (sender, e) => {
				NavigationController.PopToRootViewController(true);
			};
			await _nickViewModel.GetLocation ();
			await _nickViewModel.GetItem ();
			_imageLocation.Image = UIImage.FromFile (_nickViewModel.Location.ImageName);
			_imageNic.Image = UIImage.FromFile (_nickViewModel.PickedNick.ImageName);
			_imageThing.Image = UIImage.FromFile (_nickViewModel.Item.ImageName);
			_textGreetings.Text = "Greetings from " + _nickViewModel.LocationSearch + "!";
			_textGreetings2.Text = _textGreetings.Text;
			_resultText.Text = _nickViewModel.PickedNick.Name + " went to " + _nickViewModel.Location.Name + " and brought back " + _nickViewModel.Item.Name +"!";
			_restartButton.TitleLabel.Lines = 2;

			_saveButton.TouchUpInside += (sender, e) => {
				ScreenCapture();
				NavigationController.PopToRootViewController(true);
			};


		}

		public void ScreenCapture()
		{
			var documentsDirectory = Environment.GetFolderPath
				(Environment.SpecialFolder.Personal);

			Console.WriteLine("start capture of frame: " + new System.Drawing.SizeF(320,149));
			UIGraphics.BeginImageContext(new System.Drawing.SizeF(320,149)); 
			var ctx = UIGraphics.GetCurrentContext();
			if (ctx != null)
			{
				View.Layer.RenderInContext(ctx);
				UIImage img = UIGraphics.GetImageFromCurrentImageContext();
				UIGraphics.EndImageContext();

				// Set to display in a UIImage control _on_ the view
				//imageLogo.Image = img;

				// Save to Photos
				img.SaveToPhotosAlbum(
					(sender, args)=>{Console.WriteLine("image saved to Photos");}
				);
			}
			else
			{
				Console.WriteLine("ctx null - doesn't seem to happen");
			}
		}
	}
}
