// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PickANick.Core.ViewModels;
using PickANick.Core;

namespace PickANick.iOS
{
	public partial class ResultController : UIViewController
	{
		private readonly NickViewModel _nickViewModel = ServiceContainer.Resolve<NickViewModel>();
		public ResultController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_nickViewModel.LocationSearch = "germany";
			await _nickViewModel.GetLocation();
			_resultText.Text = _nickViewModel.PickedNick.ImageName + " went to " + _nickViewModel.Location.Name + " and brought back " + "<A THING>"+"!";
		}
	}
}
