// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using PickANick.Core.ViewModels;
using PickANick.Core;

namespace PickANick.iOS
{
	public partial class ResultController : UIViewController
	{
		private readonly NickViewModel _nickViewModel = ServiceContainer.Resolve<NickViewModel>();
		public ResultController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			_restartButton.TouchUpInside += (sender, e) => {
				NavigationController.PopToRootViewController(true);
			};
			await _nickViewModel.GetLocation ();
			await _nickViewModel.GetItem ();
			_imageLocation.Image = UIImage.FromFile (_nickViewModel.Location.ImageName);
			_imageNic.Image = UIImage.FromFile (_nickViewModel.PickedNick.ImageName);
			_imageThing.Image = UIImage.FromFile (_nickViewModel.Item.ImageName);
			_textGreetings.Text = "Greetings from " + _nickViewModel.LocationSearch + "!";
			_textGreetings2.Text = _textGreetings.Text;
			_resultText.Text = _nickViewModel.PickedNick.Name + " went to " + _nickViewModel.Location.Name + " and brought back " + _nickViewModel.Item.Name +"!";
		}
	}
}
