#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PickANick.Droid.Resource", IsApplication=true)]

namespace PickANick.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int blue = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int orange = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int red = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int yellow = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int baseball = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bowlinggreenky = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int coolnic = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int creepynic = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int egypt = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int error = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int flirtatiousnic = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int germany = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int happynic = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int life = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int londonengland = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int newyorkamerica = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int nicofthenight = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int parisfrance = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sadness = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sadnic = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sandwich = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int sarcasticnic = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int theinternet = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int tshirt = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int youthfulnic = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Text = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int adventureButton = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int greetingsImage = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int greetingsText = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int itemImage = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060001
			public const int locationField = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int nickImage = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int nickList = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int nickName = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int relativeLayout1 = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int resultText = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int submitButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LocationLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NickRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ResultLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
